mali_bifrost: fix undefined reference to `get_gl_mem_by_pid` this happened because of the gpu mali_bifrost oss driver, which does not include vendor edits in it. it throws modpost error like:
/../kernel/aarch64-gcc/bin/aarch64-linux-gnu-ld: fs/proc/base.o: in function `proc_pid_real_phymemory_read':
/../kernel/out/../fs/proc/base.c:427: undefined reference to `get_gl_mem_by_pid'

add relevant vendor edits and error fixed.

Signed-off-by: Rem01 <Rem01_Gaming@proton.me>